# One-line introductions for Elements in Style: what makes each element distinctive, and where people meet it.
# "Why it sits here" is generated on the page from the electron configuration.
import json

LAB = 'Only in research labs, a few atoms at a time.'
I = {
 1: ('The lightest and most abundant element: one proton and one electron.', 'Water, the Sun, and every organic molecule.'),
 2: ('So unreactive it forms no stable compounds, and it stays liquid down to absolute zero at normal pressure.', 'Party balloons, cooling the magnets in MRI scanners.'),
 3: ('The lightest metal: soft enough to cut with a knife, and it floats on water.', 'Rechargeable batteries in phones and electric cars.'),
 4: ('Light, stiff and almost transparent to X-rays, but its dust is toxic.', 'X-ray windows, aerospace parts, the James Webb Space Telescope’s mirrors.'),
 5: ('A hard, dark semi-metal that stars destroy rather than make.', 'Heat-proof borosilicate glass, detergents, neodymium magnets.'),
 6: ('Bonds to itself in endless chains and rings: the backbone of all known life.', 'Every living thing, pencil graphite, diamonds, fuels.'),
 7: ('Its two atoms share a triple bond so strong that nitrogen gas barely reacts.', 'Most of the air, fertilisers, proteins and DNA.'),
 8: ('Pulls electrons from almost everything; it is what makes fire and rust happen.', 'The air you breathe, water, and nearly half of Earth’s crust by mass.'),
 9: ('The most reactive element of all; it even reacts with some noble gases.', 'Fluoride toothpaste, non-stick pans, refrigerants.'),
 10: ('A noble gas that glows red-orange when electricity runs through it.', 'Neon signs, lasers.'),
 11: ('A soft metal that fizzes in water and can burst into flame.', 'Table salt, baking soda, the yellow glow of old street lamps.'),
 12: ('A light metal that burns with a blinding white flame.', 'Chlorophyll in every green leaf, lightweight alloys, flares.'),
 13: ('The most abundant metal in Earth’s crust, protected by an invisible oxide skin.', 'Drink cans, foil, aircraft, window frames.'),
 14: ('A semiconductor: doping it with traces of other elements made the computer age.', 'Computer chips, solar cells, sand and glass.'),
 15: ('Comes in white, red and black forms; the white form glows and catches fire in air.', 'DNA’s backbone, bones and teeth, fertilisers, match strikers.'),
 16: ('A bright yellow solid with no smell of its own; its compounds give rotten eggs their stink.', 'Matches, rubber tyres, sulfuric acid.'),
 17: ('A poisonous yellow-green gas that becomes harmless when bound up as salt.', 'Table salt, swimming pools, PVC plastic, disinfectants.'),
 18: ('Almost 1% of the air, and it reacts with practically nothing.', 'Light bulbs, welding gas, double-glazed windows.'),
 19: ('So reactive it bursts into a lilac flame in water.', 'Bananas, potash fertiliser, the electrical signals in your nerves.'),
 20: ('A soft metal whose compounds build bones, shells and whole mountains of limestone.', 'Bones and teeth, milk, chalk, cement.'),
 21: ('A rare, light metal Mendeleev predicted before anyone had found it.', 'Aluminium–scandium alloys in bike frames and aircraft parts.'),
 22: ('As strong as many steels but about 45% lighter, and it shrugs off corrosion.', 'Hip implants, aircraft, white paint (titanium dioxide).'),
 23: ('A little of it makes steel tough and springy.', 'Tool steels, large vanadium flow batteries.'),
 24: ('Takes a mirror polish and keeps steel from rusting.', 'Chrome plating, stainless steel, the colour of rubies and emeralds.'),
 25: ('Essential for steelmaking, and for the step of photosynthesis that splits water.', 'Steel, alkaline batteries, plant enzymes.'),
 26: ('The most-used metal on Earth, with one of the most tightly bound nuclei of all, which is why fusion in stars stops paying off here.', 'Steel, the haemoglobin in your blood, Earth’s core.'),
 27: ('A magnetic metal whose compounds give glass a deep blue.', 'Lithium-ion battery cathodes, blue glass, vitamin B12.'),
 28: ('Tough, corrosion-resistant and magnetic.', 'Stainless steel, coins, rechargeable batteries.'),
 29: ('The second-best electrical conductor; its reddish colour turns green outdoors.', 'Wiring, plumbing, the Statue of Liberty.'),
 30: ('Sacrifices itself to keep steel from rusting.', 'Galvanised steel, brass, sunscreen, hundreds of enzymes.'),
 31: ('Melts in your hand at 29.8 °C.', 'Blue and white LEDs, fast phone chips.'),
 32: ('A semiconductor that came before silicon in the first transistors.', 'Fibre-optic cables, infrared camera lenses.'),
 33: ('A notorious poison that is also a useful semiconductor ingredient.', 'Gallium arsenide chips in phones and satellites.'),
 34: ('Conducts electricity better in light than in the dark.', 'Glassmaking, dietary supplements, solar cells.'),
 35: ('One of only two elements that are liquid at room temperature; it fumes red-brown.', 'Flame retardants, water treatment, old photographic film.'),
 36: ('A noble gas whose orange light once defined the length of a metre.', 'Energy-efficient windows, photographic flash lamps.'),
 37: ('Melts just above body temperature and ignites on contact with air.', 'Atomic clocks, research lasers.'),
 38: ('Burns with a brilliant crimson flame.', 'Red fireworks and flares.'),
 39: ('Named after Ytterby, a Swedish village that gave its name to four elements.', 'YAG lasers, LED phosphors, superconductors.'),
 40: ('Almost transparent to neutrons and very hard to corrode.', 'Nuclear fuel cladding, cubic zirconia jewellery, ceramic knives.'),
 41: ('Becomes a superconductor at 9.2 K, the highest temperature of any element at normal pressure.', 'MRI and particle-accelerator magnets, jet-engine alloys.'),
 42: ('Melts above 2,600 °C and makes steel stronger at high temperatures.', 'High-strength steels; the enzymes bacteria use to fix nitrogen.'),
 43: ('The lightest element with no stable isotope, and the first ever made artificially.', 'Medical imaging: tens of millions of scans a year.'),
 44: ('A hard, rare platinum-group metal that makes contacts last.', 'Hard drives, electrical contacts, chemical catalysts.'),
 45: ('One of the rarest and most expensive metals.', 'Catalytic converters, the bright finish on white-gold jewellery.'),
 46: ('Soaks up hundreds of times its own volume of hydrogen.', 'Catalytic converters, electronics, dentistry.'),
 47: ('Conducts electricity and heat better than any other metal.', 'Jewellery, cutlery, mirrors, solar panels.'),
 48: ('A toxic metal once common in rechargeable batteries.', 'Nickel–cadmium batteries, bright yellow and red pigments.'),
 49: ('So soft you can scratch it with a fingernail, and it sticks to glass.', 'The transparent conductor in touchscreens (indium tin oxide).'),
 50: ('Bends with a crackling “tin cry”, and crumbles to powder in severe cold.', 'Solder, tin-plated steel cans, bronze.'),
 51: ('A brittle metalloid ancient Egyptians ground into eyeliner.', 'Flame retardants, lead-acid battery alloys.'),
 52: ('Rarer than gold in Earth’s crust.', 'Thin-film solar panels, rewritable discs.'),
 53: ('A dark solid that turns straight into violet vapour when warmed.', 'Iodised salt, antiseptics, your thyroid hormones.'),
 54: ('The first noble gas shown to form compounds.', 'Bright car headlights, ion engines on spacecraft, anaesthesia.'),
 55: ('One of the most reactive metals, and the one that defines the second.', 'Atomic clocks, drilling fluids.'),
 56: ('Heavy and toxic, yet its sulfate is safe to swallow because it does not dissolve.', 'Barium meals for X-rays, green fireworks.'),
 57: ('Gives the lanthanides their name.', 'Camera lenses, hybrid-car batteries.'),
 58: ('The most abundant rare-earth metal; it throws sparks when scraped.', 'Lighter flints, catalytic converters, glass polishing.'),
 59: ('Tints glass and ceramics a bright yellow-green.', 'Welders’ goggles, strong magnets, aircraft-engine alloys.'),
 60: ('Makes the strongest permanent magnets there are.', 'Headphones, electric motors, wind turbines.'),
 61: ('A rare earth with no stable isotope; nearly all of it is made in reactors.', 'Long-life nuclear batteries, luminous paint (historically).'),
 62: ('Samarium–cobalt magnets keep their strength when hot.', 'Heat-resistant magnets, bone-cancer pain treatment.'),
 63: ('Glows red or blue under UV light, which helps prove euro banknotes are real.', 'Phosphors in screens and LEDs, anti-forgery inks.'),
 64: ('Magnetic only below about 20 °C, and it absorbs neutrons extremely well.', 'MRI contrast agents, reactor safety systems.'),
 65: ('Makes a bright green glow, and its alloys change shape in a magnetic field.', 'Green phosphors, sonar and precision actuators.'),
 66: ('Keeps neodymium magnets strong when they heat up.', 'Electric-car motors, wind turbines.'),
 67: ('Has the largest magnetic moment of any naturally occurring element.', 'Pole pieces of the strongest electromagnets, surgical lasers.'),
 68: ('Amplifies the light signals that carry the internet under the oceans.', 'Fibre-optic amplifiers, pink glass, laser skin treatment.'),
 69: ('One of the rarest lanthanides.', 'Portable X-ray sources, surgical lasers.'),
 70: ('Powers some of the most precise atomic clocks ever built.', 'Atomic clocks, fibre lasers.'),
 71: ('The last and densest lanthanide.', 'Targeted cancer therapy (lutetium-177), PET-scanner crystals.'),
 72: ('Zirconium’s chemical twin, except that it gobbles neutrons instead of letting them through.', 'Reactor control rods, the insulating layers in modern chips.'),
 73: ('Almost immune to corrosion, even inside the human body.', 'Phone capacitors, surgical implants.'),
 74: ('Has the highest melting point of any metal: 3,422 °C.', 'Old light-bulb filaments, drill bits, heavy alloys.'),
 75: ('The last stable element discovered, and one of the rarest.', 'Jet-engine turbine blades.'),
 76: ('The densest natural element: a fist-sized lump weighs about as much as a bowling ball.', 'Fountain-pen nibs, electrical contacts.'),
 77: ('The most corrosion-resistant metal, and a clue to what ended the dinosaurs.', 'Spark plugs, crucibles, the old standard kilogram.'),
 78: ('A precious metal that is also a superb catalyst.', 'Catalytic converters, jewellery, the cancer drug cisplatin.'),
 79: ('So unreactive it stays shiny for thousands of years; a gram can be beaten into a sheet about a square metre wide.', 'Jewellery, electronic connectors, central-bank reserves.'),
 80: ('The only metal that is liquid at room temperature.', 'Old thermometers, fluorescent lamps, dental amalgam.'),
 81: ('Tasteless, odourless and highly toxic.', 'Infrared optics, special glass.'),
 82: ('Dense, soft and easy to melt; used since Roman times, now restricted as a poison.', 'Car batteries, radiation shielding.'),
 83: ('Technically radioactive, but with a half-life over a billion times the age of the universe.', 'Pink stomach remedies, lead-free solder, rainbow-coloured crystals.'),
 84: ('Intensely radioactive: a gram heats itself to about 500 °C.', 'Anti-static brushes for camera lenses and film.'),
 85: ('The rarest naturally occurring element: under a gram in Earth’s crust at any moment.', 'Research into targeted cancer therapy.'),
 86: ('A radioactive gas that seeps out of rocks into basements.', 'Home radon tests.'),
 87: ('So unstable that no visible lump of it has ever existed.', 'Only physics laboratories.'),
 88: ('Glows faintly blue; Marie and Pierre Curie discovered it.', 'Old luminous watch dials, cancer treatment (radium-223).'),
 89: ('Glows pale blue in the dark from its own radioactivity.', 'Targeted cancer therapy (actinium-225).'),
 90: ('About three times as abundant as uranium, and a possible nuclear fuel.', 'Old gas-lantern mantles, heat-resistant ceramics.'),
 91: ('One of the rarest and most toxic natural elements.', 'Only research.'),
 92: ('The heaviest element found in quantity in nature; its slow decay helps heat Earth’s interior.', 'Nuclear power, dating rocks.'),
 93: ('The first element heavier than uranium, made in 1940.', 'Neutron detectors, research.'),
 94: ('Made by the tonne in reactors; one isotope powers deep-space probes.', 'Nuclear weapons and fuel, the power sources of Voyager and Curiosity.'),
 95: ('The only synthetic element in many homes.', 'Smoke detectors (americium-241).'),
 96: ('So radioactive it glows; it powered instruments on Mars rovers.', 'Alpha sources in rover X-ray spectrometers.'),
 97: ('Made only in a couple of reactors, in milligram amounts.', 'Target material for making heavier elements.'),
 98: ('A fierce neutron source: one microgram gives off over two million neutrons a second.', 'Starting up reactors, finding oil and gold deposits.'),
 99: ('First found in the debris of the first hydrogen bomb.', LAB),
 100: ('The heaviest element that can be built by adding neutrons one at a time.', LAB),
 101: ('The first element made and detected one atom at a time.', LAB),
 102: ('Its discovery was disputed between laboratories in three countries for years.', LAB),
 103: ('Named after Ernest Lawrence, inventor of the cyclotron.', LAB),
 104: ('The first element past the actinides; its name was fought over in the “Transfermium Wars”.', LAB),
 105: ('Named after Dubna, the Russian town of the laboratory that helped make it.', LAB),
 106: ('The first element named after a living person, Glenn Seaborg.', LAB),
 107: ('Made by fusing chromium with bismuth, one atom at a time.', LAB),
 108: ('Predicted to be one of the densest substances of all, if enough could ever be made.', LAB),
 109: ('Named for Lise Meitner, who helped explain nuclear fission.', LAB),
 110: ('Its longest-lived known isotopes last only seconds.', LAB),
 111: ('Expected to be a heavy cousin of gold.', LAB),
 112: ('Relativity may make it behave almost like a noble gas.', LAB),
 113: ('The first element discovered in Asia.', LAB),
 114: ('Sits near a predicted “island of stability” of longer-lived superheavy nuclei.', LAB),
 115: ('Its decay chain gave the first atoms of element 113 made in Russia.', LAB),
 116: ('Its atoms survive for only milliseconds.', LAB),
 117: ('The most recently discovered element (2010).', LAB),
 118: ('The heaviest element known; theory suggests it may not even behave like a gas.', LAB),
}
assert sorted(I) == list(range(1, 119))
json.dump({z: {'hook': h, 'meet': m} for z, (h, m) in I.items()}, open('intros.json', 'w'), ensure_ascii=False, separators=(',', ':'))
print('ok', len(I))
